FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish -c Release -o /app/publish

FROM nginx:alpine AS runtime
EXPOSE 80
COPY --from=build /app/publish/wwwroot /usr/share/nginx/html